Only do the IAllowDiscussion rename on Plone 6.1 and higher.
On 6.0 the new location does not exist and you get an error if you would use the rename:

```
Error: cannot pickle modified record:
Can't pickle <class 'plone.app.discussion.behavior.IAllowDiscussion'>:
import of module 'plone.app.discussion.behavior' failed`
```